# Generated by Django 4.2.10 on 2026-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', help_text='Status of the agent (available, busy, offline)', max_length=20),
        ),
    ]
